config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # Devise authentication
  devise_for :users, skip: %i[ registration ]

  # API to feed React front end
  namespace :api do
    namespace :v1 do
      resources :books, only: %i[ index show ]
    end
  end

  # Admin
  get "/admin" => "admin#index"
  namespace :admin do
    resources :books
  end

  # ChatGPT streaming
  resources :chats, only: %i[ create index show ] do
    resources :messages, only: %i[ create ]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  # Route paths that are not known to Rails to the React router
  get "/*path" => "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  BLANK_NORMALIZER = ->(value) { nil_if_blank(value) }

  private_class_method def self.nil_if_blank(value)
    value.blank? ? nil : value
  end
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :bigint           not null, primary key
#  author     :string           not null
#  review     :text
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Book < ApplicationRecord
  normalizes :title, :author, :review, with: BLANK_NORMALIZER

  validates :title, presence: true
  validates :author, presence: true
end

app/models/chat.rb
# == Schema Information
#
# Table name: chats
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_chats_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Chat < ApplicationRecord
  belongs_to :user
  has_many :messages, -> { order("created_at ASC") }, dependent: :destroy
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id              :bigint           not null, primary key
#  content         :string           not null
#  response_number :integer          default(0), not null
#  role            :integer          default("system"), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  chat_id         :bigint
#
# Indexes
#
#  index_messages_on_chat_id  (chat_id)
#
# Foreign Keys
#
#  fk_rails_...  (chat_id => chats.id)
#
class Message < ApplicationRecord
  include ActionView::RecordIdentifier

  enum :role, { system: 0, assistant: 10, user: 20 }

  belongs_to :chat

  after_create_commit -> { broadcast_created }
  after_update_commit -> { broadcast_updated }

  def broadcast_created
    broadcast_append_later_to(
      "#{dom_id(chat)}_messages",
      partial: "messages/message",
      locals: { message: self, scroll_to: true },
      target: "#{dom_id(chat)}_messages"
    )
  end

  def broadcast_updated
    broadcast_append_to(
      "#{dom_id(chat)}_messages",
      partial: "messages/message",
      locals: { message: self, scroll_to: true },
      target: "#{dom_id(chat)}_messages"
    )
  end

  def self.for_openai(messages)
    messages.map { |message| { role: message.role, content: message.content } }
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  has_many :chats
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    @books = Book.all
  end

  def show; end

  def new
    @book = Book.new
  end

  def edit; end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to [ :admin, @book ], notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to [ :admin, @book ], notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to admin_books_path, status: :see_other, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_book
    @book = Book.find(params.expect(:id))
  end

  def book_params
    params.expect(book: [ :title, :author, :review ])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"

  before_action :authenticate_user!

  def index; end
end

app/controllers/api/v1/books_controller.rb
class API::V1::BooksController < APIController
  before_action :set_book, only: %i[show]

  def index
    books = Book.all.order(title: :asc)
    render json: books
  end

  def show
    render json: @book
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/api_controller.rb
class APIController < ApplicationController
  if Rails.env.development?
    skip_before_action :verify_authenticity_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chats_controller.rb
class ChatsController < AdminController
  respond_to :html

  before_action :authenticate_user!
  before_action :set_chat, only: %i[show]

  def index
    @chats = current_user.chats
  end

  def show
    respond_with(@chat)
  end

  def create
    @chat = Chat.create(user: current_user)
    respond_with(@chat)
  end

  private

  def set_chat
    @chat = current_user.chats.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!

  def create
    @message = Message.create(message_params.merge(chat_id: params[:chat_id], role: "user"))

    GetAIResponse.perform_later(@message.chat_id)

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      flash_type
    end
  end
end

app/views/admin/books/_form.html.haml
= form_for [ :admin, book ] do |f|
  - if book.errors.any?
    #error-explanation
      %h2 #{pluralize(book.errors.count, "error")} prohibited this book from being saved:
      %ul
        - book.errors.full_messages.each do |message|
          %li= message

  .mb-3
    = f.label :title, class: "form-label"
    = f.text_field :title, class: "form-control"
  .mb-3
    = f.label :author, class: "form-label"
    = f.text_field :author, class: "form-control"
  .mb-3
    = f.label :review, class: "form-label"
    = f.textarea :review, class: "form-control"
  .actions.mb-3
    = f.submit 'Save', class: "btn btn-outline-primary"

app/views/admin/books/edit.html.haml
%h1 Editing book

= render 'form', book: @book

= link_to 'Show', [ :admin, @book ]
\|
= link_to 'Back', admin_books_path

app/views/admin/books/index.html.haml
%h1 Listing books

%table.table
  %thead
    %tr
      %th{ scope: "col" } Title
      %th{ scope: "col" } Author
      %th{ scope: "col" } Review
      %th{ scope: "col" }

  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.author
        %td= book.review
        %td
          = link_to 'Show', [ :admin, book ]
          = link_to 'Edit', edit_admin_book_path(book)
          = link_to 'Destroy', [ :admin, book ], method: :delete,
            data: { turbo_method: :delete, confirm: 'Are you sure?' }

= link_to 'New Book', new_admin_book_path

app/views/admin/books/new.html.haml
%h1 New book

= render 'form', book: @book

= link_to 'Back', admin_books_path

app/views/admin/books/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @book.title
%p
  %b Author:
  = @book.author
%p
  %b Review:
  = @book.review

= link_to 'Edit', edit_admin_book_path(@book)
\|
= link_to 'Back', admin_books_path

app/views/admin/index.html.haml
%h1 Admin Stuff

= link_to "Chat", chats_path, method: :post, data: { turbo_method: :post }

app/views/chats/_chat.html.haml
%tr
  %td= link_to chat.id, chat

app/views/chats/index.html.haml
%h1 Chat Bot List

%table.table
  = render @chats

app/views/chats/show.html.haml
%h1 Chat Bot

%div{style: "height: 400px;"}
  .overflow-y-auto.mh-100
    = turbo_stream_from "#{dom_id(@chat)}_messages"
    %div{id: "#{dom_id(@chat)}_messages"}
      = render @chat.messages
  = render partial: "messages/form", locals: { chat: @chat }

app/views/layouts/_flash_messages.html.haml
- flash.each do |flash_type, message|
  %div{class: "alert #{bootstrap_class_for(flash_type)} alert-dismissible fade show", role: "alert"}
    %button.btn-close{ type: "button", "data-bs-dismiss": "alert", "aria-label": "Close" }
    = message

app/views/layouts/admin.html.haml
!!!
%html{"data-bs-theme" => "dark"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}
    %title= content_for(:title) || "Personal Website"
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}
    %meta{content: "yes", name: "mobile-web-app-capable"}
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{href: "/icon.png", rel: "icon", type: "image/png"}
    %link{href: "/icon.svg", rel: "icon", type: "image/svg+xml"}
    %link{href: "/icon.png", rel: "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
  %body
    %nav.navbar.bg-body-tertiary.navbar-expand-lg.navbar-light
      .container.container-fluid
        = link_to "Admin", admin_path, class: "navbar-brand"
        %button.navbar-toggler{type: "button", "data-bs-toggle": "collapse",
          "data-bs-target": "#navbarSupportedContent", "aria-controls": "navbar-supported-content",
          "aria-expanded": "false", "aria-label": "Toggle navigation"}
          %span.navbar-toggler-icon
        #navbar-supported-content.collapse.navbar-collapse
          %ul.navbar-nav
            %li.nav-item
              = link_to "Books", admin_books_path, class: "nav-link"
            %li.nav-item
              = link_to 'Log Out', destroy_user_session_path, method: :delete,
                class: "nav-link", data: { turbo_method: :delete, confirm: 'Are you sure?' }
    .container
      = render "layouts/flash_messages"
      = yield

app/views/layouts/application.html.haml
!!!
%html{"data-bs-theme" => "dark"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}
    %title= content_for(:title) || "Personal Website"
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}
    %meta{content: "yes", name: "mobile-web-app-capable"}
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{href: "/icon.png", rel: "icon", type: "image/png"}
    %link{href: "/icon.svg", rel: "icon", type: "image/svg+xml"}
    %link{href: "/icon.png", rel: "apple-touch-icon"}
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
  %body
    = yield

app/views/messages/_form.html.haml
= turbo_frame_tag "#{dom_id(chat)}_message_form" do
  = form_with(model: Message.new, url: [chat, chat.messages.new]) do |form|
    .input-group
      = form.text_area :content, rows: 4, class: "form-control", autofocus: true, "x-on:keydown.cmd.enter" => "$event.target.form.requestSubmit();"
      = form.button "Send", type: :submit, class: "btn btn-outline-primary"

app/views/messages/_message.html.haml
%div{:id => "#{dom_id(message)}_messages"}
  - if message.user?
    .alert.alert-dark{role: "alert"}
      = message.content
  - else
    .alert.alert-light{role: "alert"}
      = message.content